# Generated by Django 2.2.2 on 2019-06-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandsOffApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='owner',
            name='contact_info',
            field=models.CharField(default='Phone number: ', max_length=256),
            preserve_default=False,
        ),
    ]
