# Generated by Django 2.2.2 on 2019-07-13 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HandsOffApp', '0002_auto_20190628_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HandsOffApp.Category'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='password',
            field=models.CharField(max_length=64),
        ),
    ]
