# Generated by Django 2.2.2 on 2019-07-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandsOffApp', '0003_auto_20190713_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
