# Generated by Django 2.2.2 on 2019-07-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandsOffApp', '0004_auto_20190715_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='owner',
            name='contact_info',
            field=models.TextField(max_length=256),
        ),
    ]
